line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort
ignore = ["E501"]         # don't gate on line length for now

[format]
quote-style = "preserve"
