line-length = 100
target-version = "py310"

[lint]
# pycodestyle (E), pyflakes (F), isort (I)
select = ["E", "F", "I"]
# Ignore long lines for now + allow multiple statements on one line
ignore = ["E501", "E701", "E702"]

[format]
quote-style = "preserve"
