name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  PYTHONUTF8: "1"

jobs:
  lint:
    name: Lint (ruff, flake8, pylint, pyright)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install dev toolchain
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Show versions
        run: |
          python -V
          ruff --version
          black --version
          isort --version-number
          flake8 --version
          pylint --version || true
          pyright --version || true
          pre-commit --version

      - name: Run pre-commit on all files
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pre-commit run --all-files

  unit-tests:
    name: Unit tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pytest (unit)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q -m "not integration" --maxfail=1 --disable-warnings

  integration:
    name: Integration tests (smoke + optional @integration)
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Prepare DB (fresh) and seed defaults
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p db
          rm -f db/auditron.db
          python scripts/seed_db.py --init-defaults

      - name: Orchestrator smoke run (no hosts)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python auditron.py --resume

      - name: Run pytest (marked integration) if present
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: bash
        run: |
          shopt -s nullglob
          files=(tests/integration/test_*.py)
          if [ ${#files[@]} -gt 0 ]; then
            pytest -q -m integration --maxfail=1 --disable-warnings
          else
            echo "No integration tests found; skipping."
          fi
